[package]
name = "moon-phases"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
chrono = "0.4.28"
env_logger = "0.10.0"
leptos = {version= "0.4.10", features = ["ssr"] }
log = "0.4.20"
moon-calc = "1.0.0"
