[tasks.run]
command = "cargo"
args = ["run",  "--bin=moon-phases"]

[tasks.custom-css]
command = "cargo"
args = ["run",  "--bin=build-css"]

[tasks.leptos-rustfmt]
command = "leptosfmt"
args = ["./src"]

[tasks.dev]
run_task = {name = ["custom-css", "leptos-rustfmt", "run"], parallel = true }
