[tasks.run]
command = "cargo"
args = ["run",  "--bin=moon-phases"]

[tasks.custom-css]
command = "cargo"
args = ["run",  "--bin=build-css"]

[tasks.dev]
run_task = {name = ["custom-css", "run"], parallel = true }
